openshift/template.yaml

So it's not the `maven-index-checker` after all what makes the container eat so much memory.
`Boto` uses a lot of memory when downloading/uploading big file from/to S3.
The archive with pre-built maven index has 560MB and the container then uses almost 2GB.
Other way to solve this would be to revert using S3 and having the index in the image, but I don't like that.

Increase memory limit to handle boto being a memory hog

---

f8a-jobs.py
f8a_jobs/scheduler.py

```
Traceback (most recent call last):
File "/usr/lib64/python3.4/site-packages/apscheduler/util.py", line 268, in ref_to_obj
obj = __import__(modulename, fromlist=[rest])
ImportError: No module named 'bayesian_jobs'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/bin/f8a-jobs.py", line 90, in <module>
manager.run()
File "/usr/lib/python3.4/site-packages/flask_script/__init__.py", line 412, in run
result = self.handle(sys.argv[0], sys.argv[1:])
File "/usr/lib/python3.4/site-packages/flask_script/__init__.py", line 383, in handle
res = handle(*args, **config)
File "/usr/lib/python3.4/site-packages/flask_script/commands.py", line 216, in __call__
return self.run(*args, **kwargs)
File "/usr/bin/f8a-jobs.py", line 65, in …
```

Remove old default jobs

---

hack/install_maven-index-checker.sh

It contains a [commit](https://github.com/fabric8-analytics/maven-index-checker/commit/ea1578c5ac369479a5d74c1c4fb9f078e97e3015) with which we get the specified range of packages from the newest end of index (instead of the oldest).

maven-index-checker moved to fabric8-analytics repo

---

f8a_jobs/swagger.yaml

Since we have all the "popular" packages already analysed.

Don't sort by popularity by default

---

f8a_jobs/handlers/npm_popular_analyses.py

Scheduling NPM popular packages stopped working because "star" category was removed and instead "depended" was added (and "depended" has different class name for the link that we use).

Fix scheduling popular NPM packages (now most depended on)

---

README.md

Hi, unless I'm mistaken, the \ characters at EOLNs (ie. continuation characters) will be preserved in the JSON because the whole string is enclosed in apostrophes. There's also problem in Swagger UI that displays \ as well (but it will be another issue ;)

Updated JSON data in the example

---

f8a_jobs/auth.py

This will enable to access jobs service even for not public organization
members.

Add read organization scope for OAuth

---

Dockerfile

Protobuf needs to be installed from source to workaround
https://github.com/google/protobuf/issues/1296

Bump worker hash & add protobuf hack

---

Dockerfile

https://github.com/fabric8-analytics/fabric8-analytics-worker/commit/e8875ac63e362df42a4973fcd84880ade0a14d02 adds `semantic_version` into requirements.
Fixes:
```
coreapi-jobs            | ImportError: No module named 'semantic_version'
```

Bump worker version to pull in semantic_version

---

f8a_jobs/handlers/base.py
f8a_jobs/handlers/nuget_popular_analyses.py

because libraries.io provide only first 3000 popular packages

[Nuget] get list of popular packages from nuget org instead of libraries.io

---

f8a_jobs/handlers/base.py
f8a_jobs/handlers/maven_popular_analyses.py
f8a_jobs/handlers/npm_popular_analyses.py
f8a_jobs/handlers/nuget_popular_analyses.py
f8a_jobs/handlers/python_popular_analyses.py
f8a_jobs/swagger.yaml

It's just equivalent of nversions==1
When `latest_version_only` was set to `True`, the `nversions` was ignored and only one latest version of each package was scheduled.
Which is exactly what `nversions==1` does, because `nversions` specifies how many latest versions of each package to schedule.
For a record, the `latest_version_only` was added with: 29062ca, 36cad98, 0e2b45d

Get rid of latest_version_only

---

f8a_jobs/default_jobs/bigQueryJob.yaml
f8a_jobs/default_jobs/cveCheckJob.yaml
f8a_jobs/default_jobs/cveMavenCheckJob.yaml
f8a_jobs/default_jobs/githubGatheringJob.yaml

```
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/f8a_jobs/scheduler.py", line 117, in schedule_job
coreapi-jobs            |     raise ScheduleJobError("Unable to parse format for 'misfire_grace_time': '%s'" % misfire_grace_time)
coreapi-jobs            | f8a_jobs.scheduler.ScheduleJobError: Unable to parse format for 'misfire_grace_time': '1 year'
```
https://github.com/wroberts/pytimeparse/issues/7

timeparse can't handle years

---

Dockerfile
f8a_jobs/default_jobs/cveCheckJob.yaml
f8a_jobs/default_jobs/cveMavenCheckJob.yaml

Since https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/292 we haven't used Snyk's outdated vulnerability db anymore and use OSS Index instead.
Let's run the [cveCheckJob](https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/default_jobs/cveCheckJob.yaml) again.
It also [has support for Maven now](https://github.com/fabric8-analytics/fabric8-analytics-worker/commit/de4e85c3bf573888374dc1794f87f580918ebe25
) so we can pause [cveMavenCheckJob](https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/default_jobs/cveMavenCheckJob.yaml)
Would be nice to also wait for https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/340

Un-pause cveCheckJob & pause cveMavenCheckJob

---

f8a_jobs/handlers/aggregate_github_manifest_pkgs.py

This PR is related to last work item of  issue: https://github.com/openshiftio/openshift.io/issues/983.
which needs the structure of collected manifest files as per format given in https://github.com/sara-02/fabric8-analytics-stack-analysis/blob/e5265731a79213c045434cdf1d0db5a9c2ef0ab0/analytics_platform/kronos/schema/raw_input_manifest.json.
So, In this PR, an attempted is made to collect manifest with new structure as mentioned above and mean-while retain the previous structure code also.

create manifest file with new structure

---

f8a_jobs/handlers/base.py
f8a_jobs/handlers/golang_popular_analyses.py
f8a_jobs/swagger.yaml

I don't know how many golang packages is out there, but http://go-search.org/api?action=packages contains over 750000, so I guess it's most of them. And they seem to be sorted by popularity too.
For now the getting of latest commit works only for packages on github.com, but it's still over 730000.
Requires https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/376

Fix golang popular packages job

---

openshift/template.yaml

Because we have PV in RWO mode.

[openshift] Switch to recreate deployment strategy

---

f8a_jobs/swagger.yaml

So I don't have to select it each time

Set default value to job_type parameter of 'GET /jobs'

---

f8a_jobs/swagger.yaml

Do I really need to **always** check/switch this value before submitting a job ?

Change default value of 'state' from 'paused' to 'running'

---

tests/handlers/test_aggregate_crowd_source_tags.py

Fix issues #377, #378, #379, and #380: Braces are not required around condition in `assert` statement
- [x ] Bug fix (non-breaking change which fixes an issue)

Fix issues #377, #378, #379, and #380: Braces are not required around condition in assert statement

---

f8a_jobs/graph_ingestion.py
requirements.in
requirements.txt
tests/requirements.in
tests/requirements.txt

Currently flow name is decided based on environment variable "WORKER_ADMINISTRATION_REGION" so it can have only 2 default flow names i.e. bayesianFlow/bayesianApiFlow.
In that case for Golang flow name has to be sent with request body which makes is difficult to manage if we update flow name. To avoid that API calls are set as default i.e.bayesianApiFlow/newPackageFlow, because these flows will be triggered by front end components like API server/Backbone and other Ingestion flows like bayesianFlow, bayesianAnalysisFlow, newPackageAnalysisFlow will be called by back end components only like Github refresh where we can send flow name with body and update if needed.
Also updated the worker version to latest.

chore: Golang flow name handling

---

f8a_jobs/api_spec.yaml
f8a_jobs/graph_ingestion.py
openshift/template.yaml
tests/test_graph_ingestion.py

Introduced new auth free ingestion end points which will be used internally and can not be exposed through public route.
https://app.swaggerhub.com/apis/jparsai/Jobs_API/0.1?loggedInWithGitHub=true

fix: auth free ingestion end point for internal use

---

f8a_jobs/graph_ingestion.py
openshift/template.yaml

Exposing "api/v1" end point via external route to get access to existing authentication API's

fix: Expose v1 end points via public route.
