f8a-jobs.py, f8a_jobs/scheduler.py
Reverts fabric8-analytics/fabric8-analytics-jobs#35
=> Revert "Remove old default jobs"

f8a_jobs/handlers/maven_popular_analyses.py
I don't think this will actually fix the maven-index-checker issues, but better be sure.
=> Clean up after maven-index-checker run

f8a_jobs/handlers/npm_popular_analyses.py
=> Fix for NPM analyses if there are no versions present

Dockerfile, f8a_jobs/handlers/maven_popular_analyses.py
Requires https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/40
=> [maven-index-checker] analyze only one version of each package

f8a_jobs/handlers/maven_popular_analyses.py
And upload index only if it has changed.
=> Carefully clean up after maven-index-checker

f8a_jobs/handlers/maven_popular_analyses.py
Temporary workaround for super-annoying https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/47.
=> Avoid postgres until fabric8-analytics-worker/issues/47 is fixed

f8a_jobs/handlers/npm_popular_analyses.py
- also fixes issue with not being to able to schedule multiple versions for popular packages
=> Make it possible to only schedule latest version for npm components

Dockerfile, f8a-jobs.py
Related: https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/47
=> Initialize Selinon only once on startup

f8a_jobs/api_v1.py
Reverts fabric8-analytics/fabric8-analytics-jobs#58
=> Revert "Simplify liveness probe for now"

f8a_jobs/api_v1.py
=> Return 410 when deleting nonexistent job

f8a_jobs/api_v1.py, f8a_jobs/swagger.yaml
=> Return 200 on HTTP delete

f8a-jobs.py
=> List all available paths

f8a_jobs/api_v1.py
=> Return HTTP 404 when PUT is issued on unknown jobs

f8a_jobs/api_v1.py, f8a_jobs/swagger.yaml
=> HTTP 200 on success PUT requests

f8a_jobs/defaults.py
Related: https://github.com/fabric8-analytics/fabric8-analytics-server/pull/84
=> Better disable auth

f8a_jobs/handlers/base.py
Related: https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/164
=> Add PackageGraphImporterTask to default tasks

f8a_jobs/handlers/npm_popular_analyses.py
it was scheduling count-1 analyses
=> Fix _use_npm_popular()

f8a_jobs/api_v1.py
Fixes: https://github.com/fabric8-analytics/fabric8-analytics-common/issues/219
=> Return 400 instead of 401 on generic errors

f8a_jobs/swagger.yaml
=> Use PUT method for logout

Dockerfile
Related: https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/260
=> Remove google.protobuf hack

f8a_jobs/swagger.yaml
=> Revisit reported status codes in Swagger

f8a_jobs/api_v1.py, f8a_jobs/swagger.yaml
=> Report 401 if user is not logged in on logout

f8a_jobs/analyses_report.py, f8a_jobs/handlers/aggregate_topics.py, f8a_jobs/handlers/base.py, f8a_jobs/handlers/clean_postgres.py, f8a_jobs/handlers/sync_to_graph.py, f8a_jobs/models.py
=> Wrap (try-except) all db access and rollback on error

f8a_jobs/handlers/aggregate_github_manifest_pkgs.py
The action item for the issue https://github.com/openshiftio/openshift.io/issues/811 .
Thanks
=> extract version information during manifest file creation.

f8a_jobs/handlers/aggregate_topics.py, f8a_jobs/handlers/sync_to_graph.py
Fixes https://github.com/openshiftio/openshift.io/issues/1003
=> Fix 'E722 do not use bare except'

f8a_jobs/handlers/golang_popular_analyses.py
Fix pylint warning introduced by the last merge.
=> Fix pylint warning (minor)

f8a_jobs/handlers/aggregate_github_manifest_pkgs.py
This fix is related to the new-manifest creation,
=> GH new-manifest fix

f8a_jobs/api_v1.py
=> Get authorization token from headers as well

f8a_jobs/handlers/sqs_purge.py
=> Specify region_name

f8a_jobs/scheduler.py
=> Make all jobs trackable

f8a_jobs/utils.py
=> Report job dates in UTC

f8a_jobs/handlers/sqs_purge.py
=> Fix purging queues - request QueueUrl first

f8a_jobs/handlers/golang_popular_analyses.py
Fixes issue:
* https://github.com/fabric8-analytics/fabric8-analytics-jobs/issues/208
=> Select base url of the github repo to fetch latest commit tag

check-docstyle.sh
Previous status: https://fabric8-analytics.github.io/dashboard/repository_fabric8-analytics-jobs.html
This change fix the problem with two source files that were not checked.
=> Update check-docstyle.sh script to check all files

f8a-jobs.py, f8a_jobs/handlers/aggregate_github_manifest_pkgs.py, f8a_jobs/handlers/base.py, f8a_jobs/handlers/clean_postgres.py, f8a_jobs/handlers/error.py, f8a_jobs/handlers/flow.py, f8a_jobs/handlers/github_manifests.py, f8a_jobs/handlers/github_most_starred.py, f8a_jobs/handlers/maven_popular_analyses.py, f8a_jobs/handlers/npm_popular_analyses.py, f8a_jobs/handlers/nuget_popular_analyses.py, f8a_jobs/handlers/python_popular_analyses.py, f8a_jobs/handlers/selective_flow.py, f8a_jobs/handlers/sync_to_graph.py, f8a_jobs/models.py, f8a_jobs/scheduler.py, f8a_jobs/utils.py
Partial fix for https://github.com/openshiftio/openshift.io/issues/1230
=> Fix issues in existing documentation strings

openshift/template.yaml
Related: https://github.com/openshiftio/openshift.io/issues/1298
=> [openshift] Add persistent volume

check-docstyle.sh, run-linter.sh
@jpopelka (your) new tests should be checked by pylinter etc. etc. :)
=> Run pylinter and docstyle checker for (new) tests

f8a_jobs/analyses_report.py, f8a_jobs/auth.py, f8a_jobs/handlers/maven_releases.py, f8a_jobs/handlers/npm_popular_analyses.py, f8a_jobs/handlers/nuget_popular_analyses.py, f8a_jobs/handlers/python_popular_analyses.py, f8a_jobs/handlers/selective_flow.py, f8a_jobs/handlers/sync_to_graph.py, f8a_jobs/models.py
Let's increase the Pydocstyle score from 21% to even higher numbers :) https://fabric8-analytics.github.io/dashboard/dashboard.html
=> Fix docstrings 3rd attempt

f8a-jobs.py, f8a_jobs/__init__.py, f8a_jobs/error.py, f8a_jobs/handlers/error.py, f8a_jobs/handlers/flow.py, f8a_jobs/handlers/github_manifests.py, f8a_jobs/handlers/github_most_starred.py, f8a_jobs/handlers/golang_popular_analyses.py, f8a_jobs/handlers/maven_popular_analyses.py, setup.py, tests/test_utils.py
the last changes I'm able to write myself ;)
=> Fix docstrings 4th attempt

f8a_jobs/api_v1.py, f8a_jobs/handlers/__init__.py, f8a_jobs/handlers/aggregate_github_manifest_pkgs.py, f8a_jobs/models.py
At last! The remaining docstrings needed to have 100% coverage :)
=> Fix docstrings 5th attempt

cico_run_pydoc.sh
the very last step needed to close https://github.com/openshiftio/openshift.io/issues/1230
=> Script to run pydocchecker in CI

Dockerfile, hack/_copr_fche_pcp.repo, hack/jobs+pmcd.sh
Fixes https://github.com/openshiftio/openshift.io/issues/1506
=> inject pcp pmcd agent for remote monitoring

f8a_jobs/swagger.yaml
It was moved to [Debug] in 52d6f8d26
=> Change /jobs/queue-purge to /debug/queue-purge

Dockerfile, f8a_jobs/api_v1.py, f8a_jobs/handlers/__init__.py, f8a_jobs/handlers/kronos_data_update.py, f8a_jobs/swagger.yaml
Depends on https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/493 to be merged first
For issue openshiftio/openshift.io#1694
=> Add job for kronos data updater

f8a_jobs/api_v1.py, f8a_jobs/utils.py
Potential fix for: https://github.com/fabric8-analytics/fabric8-analytics-jobs/issues/244
=> Use bearer token to fetch org memberships

f8a_jobs/api_v1.py, f8a_jobs/handlers/book_keeping.py, f8a_jobs/swagger.yaml
Follow-up of #248 
Related to https://github.com/openshiftio/openshift.io/issues/2186
=> Allow to get upstreams only for given ecosystem or ecosystem/package

f8a_jobs/handlers/book_keeping.py
=> [BookKeeping] one more tweak

f8a_jobs/handlers/book_keeping.py
See https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/514
Trivial change, will merge myself.
=> [BookKeeping.upstreams] Don't show active flag

README.md
=> Trigger rebuild

f8a_jobs/handlers/book_keeping.py, f8a_jobs/swagger.yaml
Related to https://github.com/openshiftio/openshift.io/issues/2240
=> [BookKeeping/upstreams] Be able to show active records only

Dockerfile
There was error reporting service - Sentry introduced, which brought some changes in code and bump of selinon version as well.
=> Bump worker version

f8a_jobs/api_v1.py, f8a_jobs/graph_sync.py, f8a_jobs/swagger.yaml
For: https://github.com/openshiftio/openshift.io/issues/2315
=> Add offset and limit capability to APIs

Dockerfile, f8a_jobs/handlers/book_keeping.py
Requires https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/537
Related to https://github.com/openshiftio/openshift.io/issues/2221
=> [Bookkeeping] Show also timestamps of when worker started/ended

f8a_jobs/api_v1.py, f8a_jobs/handlers/__init__.py, f8a_jobs/handlers/invoke_graph_sync.py, f8a_jobs/swagger.yaml
For: https://github.com/openshiftio/openshift.io/issues/2315
=> Add worker to invoke graph sync in parallel

Dockerfile.rhel
For: https://github.com/openshiftio/openshift.io/issues/3339
Fixes: https://github.com/fabric8-analytics/fabric8-analytics-jobs/issues/280
=> Bump worker version for rhel image

check-bashscripts.sh, check-docstyle.sh, cico_setup.sh, list-todo.sh, measure-cyclomatic-complexity.sh, measure-maintainability-index.sh, run-linter.sh, runtest.sh
Problem description: https://github.com/openshiftio/openshift.io/issues/3751
=> Fix shellcheck issues

Dockerfile, Dockerfile.rhel, openshift/template.yaml
Change secret naming based on new convention
=> change secret name as per new convention

f8a_jobs/graph_ingestion.py, requirements.in, requirements.txt, tests/test_graph_ingestion.py
Ingestion of Go package having pseudo version is not supported hence validation for pseudo version is placed in jobs to avoid such packages and ingest only semver versions.
=> fix: Validation for Golang semver version ingestion.

.github/workflows/ci-build-image.yml, .github/workflows/ci-build.yml, .github/workflows/slash-command.yml, README.md, hack/exec_tests.sh, qa/measure-cyclomatic-complexity.sh, qa/measure-maintainability-index.sh, qa/runtest.sh
This PR adds github actions as the CI
=> chore: Migrate CI to Gh actions

f8a_jobs/graph_ingestion.py, f8a_jobs/utils.py
Changed user validation process from secrete based validation to existing token based validation, because its is impossible to know Prod secrets for testing something, which makes things hard if we need to debug any issue, if we use tokens for validation like V1 APIs things will be easy. 
The reason we used secret for auth is that it will not expire with time like tokens, but now we have internal API's so we can use tokens for V2 APIs as well.
=> fix: user authentication

openshift/template.yaml
changed strategy for replica updates
=> fix: Strategy update

openshift/template.yaml
Reverts fabric8-analytics/fabric8-analytics-jobs#413
=> Revert "fix: Strategy update"

Dockerfile.app-sre
As UBI is causing issue in Staging we are trying to check the issue with CentOS base image.
=> Rollback to CentOS base image.

f8a_jobs/user_cache.py, openshift/template.yaml
Using different secret to validate user in Gemini and updated query to collect user data.
=> chore: Modifications in gemini query and secret.

f8a_jobs/api_spec.yaml, f8a_jobs/graph_ingestion.py, f8a_jobs/user_cache.py
Introducing API for cache refresh.
=> chore: Cache refresh API.

f8a_jobs/api_spec.yaml, f8a_jobs/defaults.py, f8a_jobs/graph_ingestion.py, f8a_jobs/user_cache.py, f8a_jobs/utils.py, openshift/template.yaml
- Added new API for listing users in cache.
- Changed validation mechanism.
=> chore: New API to listing PVC files

openshift/template.yaml
Reverts fabric8-analytics/fabric8-analytics-jobs#434
=> chore: updating replica.
